version: "1.0"
info:
  model: int-scaffold
packages:
- name: Siqatestawsstagenonprod23Project
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: JMS2waySSL
  version: "1.0"
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
- name: JMSTest
  version: "1.0"
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
- name: SSL_JDBC_Test
  version: "1.0"
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:DatabaseNewAcc
  packages:
  - name: Siqatestawsstagenonprod23Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqatestawsstagenonprod23.integrations:Call_refData
  packages:
  - name: Siqatestawsstagenonprod23Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqatestawsstagenonprod23.referencedata:refData
  packages:
  - name: Siqatestawsstagenonprod23Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqatestawsstagenonprod23.integrations:JMSFlowTest
  packages:
  - name: Siqatestawsstagenonprod23Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: publisher:publisher
  packages:
  - name: JMSTest
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: project.siqatestawsstagenonprod23.integrations:JMS_JNDI_SSL
  packages:
  - name: Siqatestawsstagenonprod23Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: jms2wayssl_publisher:jms2wayssl_publisher
  packages:
  - name: JMS2waySSL
    version: "1.0"
- serviceName: project.siqatestawsstagenonprod23.integrations:SIQAAdapterFlow
  packages:
  - name: Siqatestawsstagenonprod23Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: Siqatestawsstagenonprod23Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqatestawsstagenonprod23.integrations:SSL_JDBC_test
  packages:
  - name: Siqatestawsstagenonprod23Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: SSL_JDBC_Test.services:insert_ssl
  packages:
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqatestawsstagenonprod23.integrations:test
  packages:
  - name: Siqatestawsstagenonprod23Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.trustStore
  : ""
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.portNumber
  : "3306"
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.networkProtocol
  : tcp
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.password
  : "{AES}D6/2AGfsSWDOcWCLrORnEQ=="
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.serverName
  : 9.46.196.248
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.user
  : siqatest
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.databaseName
  : MYSQL_DATABASE
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.dbType
  : MySQL
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.poolable
  : "false"
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.keyStore
  : ""
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionEnabled
  : "false"
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionSettings.driverType
  : driverTest
  ? artConnection.Siqatestawsstagenonprod23Project.project.siqatestawsstagenonprod23.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAcc.connectionManagerSettings.blockingTimeout
  : "1000"
