version: "1.0"
info:
  model: int-scaffold
packages:
- name: Siqatestawsstagenonprod23Project
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: JMS2waySSL
  version: "1.0"
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
- name: JMSTest
  version: "1.0"
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
- name: SSL_JDBC_Test
  version: "1.0"
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqatestawsstagenonprod23.integrations:JMSFlowTest
  packages:
  - name: Siqatestawsstagenonprod23Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: publisher:publisher
  packages:
  - name: JMSTest
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: project.siqatestawsstagenonprod23.integrations:JMS_JNDI_SSL
  packages:
  - name: Siqatestawsstagenonprod23Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: jms2wayssl_publisher:jms2wayssl_publisher
  packages:
  - name: JMS2waySSL
    version: "1.0"
- serviceName: project.siqatestawsstagenonprod23.integrations:SSL_JDBC_test
  packages:
  - name: Siqatestawsstagenonprod23Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: SSL_JDBC_Test.services:insert_ssl
  packages:
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
